# Generated by Django 4.2.29 on 2026-03-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(blank=True, null=True)),
                ('quality_level', models.CharField(blank=True, max_length=32, null=True)),
                ('aqi_index', models.IntegerField(blank=True, null=True)),
                ('aqi_rank', models.IntegerField(blank=True, null=True)),
                ('pm25', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pm10', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('so2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('co', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('o3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'pm25_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(blank=True, null=True)),
                ('max_temperature', models.IntegerField(blank=True, null=True)),
                ('min_temperature', models.IntegerField(blank=True, null=True)),
                ('weather', models.CharField(blank=True, max_length=64, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('weekday', models.CharField(blank=True, max_length=16, null=True)),
                ('aqi', models.IntegerField(blank=True, null=True)),
                ('aqi_level', models.CharField(blank=True, max_length=32, null=True)),
                ('wind_power', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'weather_data',
                'managed': False,
            },
        ),
    ]
