# Generated by Django 4.2.29 on 2026-03-09 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airqualitydata',
            options={'managed': False, 'verbose_name': '空气质量数据', 'verbose_name_plural': '空气质量数据'},
        ),
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'managed': False, 'verbose_name': '天气数据', 'verbose_name_plural': '天气数据'},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=64, verbose_name='显示名称')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='手机号')),
                ('bio', models.CharField(blank=True, default='', max_length=255, verbose_name='个人简介')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'user_profile',
            },
        ),
    ]
